name: "cac"

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'
    - cron: '40 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install jq
        run: |
          sudo apt update >>/dev/null
          sudo apt install jq -y

      - name: install jo
        run: |
          sudo apt install gcc git automake autoconf -y
          git clone 'https://github.com/jpmens/jo.git' '/tmp/jo'
          echo 'cd /tmp/jo' >>/tmp/jo_install.sh
          echo 'autoreconf -i' >>/tmp/jo_install.sh
          echo './configure' >>/tmp/jo_install.sh
          echo 'make check' >>/tmp/jo_install.sh
          echo 'make install' >>/tmp/jo_install.sh
          chmod -R 0755 '/tmp/jo_install.sh'
          sudo '/tmp/jo_install.sh'
          
      - name: download bark_shell
        run: |
          sudo curl -L -o '/usr/bin/bark' 'https://raw.githubusercontent.com/invalidunit/bark_shell/main/bark'
          sudo chmod -R 0755 '/usr/bin/bark'
          
      - name: download cac
        run: |
          sudo curl -L -o '/usr/bin/cac' 'https://raw.githubusercontent.com/invalidunit/check_change/main/cac'
          sudo chmod -R 0755 '/usr/bin/cac'

      - name: cac
        if: success()
        env:
          _repo: ${{ github.repository }}
          _key: ${{ secrets._key }}
        run: |
          cac './Library/' 
          
      - name: save caches if local change
        if: success()
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
          git add .
          if ! git diff --staged --exit-code 1>>/dev/null; then
            git commit -m 'save caches'
            git push
          fi
          
      - name: download remove_all_actions
        run: |
          sudo curl -L -o '/usr/bin/remove_all_actions' 'https://raw.githubusercontent.com/invalidunit/action/main/remove_all_actions'
          sudo chmod -R 0755 '/usr/bin/remove_all_actions'

      - name: remove all old actions
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          remove_all_actions
